### ISSUE TITLE
Ldproof Error

### ISSUE THREAD

**Issue by hendersonweb** [danubetech/key-formats-java#8]
Hallo,

When I try touse ldproof to sign a VC i get the following error. I have included the dependancy of keyformats in my pom file. But still it does come. How to resolve it? Any ideas?

java.util.ServiceConfigurationError: com.danubetech.keyformats.crypto.provider.Ed25519Provider: Provider com.danubetech.keyformats.crypto.provider.impl.NaClSodiumEd25519Provider could not be instantiated
	at com.danubetech.verifiablecredentials.VerifyCredentialTest.testcredential(VerifyCredentialTest.java:93)

**Comment by peacekeeper** [comment]
You probably have to install [libsodium](https://doc.libsodium.org/).

Depending on your operating system, e.g.:

```
sudo apt-get install libsodium23
```

**Comment by hendersonweb** [comment]
I'm using Windows OS. So Is there any specific software libs that have to be installed?. I tried to compile Key-format-java repository separately and its working fine. But when i try to sign some VC then it gives an error.

**Comment by peacekeeper** [comment]
I'm not sure how to install libsodium on Windows, maybe try to search for that information.

Another option is to use the [TinkEd25519Provider](https://github.com/danubetech/key-formats-java/blob/main/src/main/java/com/danubetech/keyformats/crypto/provider/impl/TinkEd25519Provider.java) service instead of the [NaClSodiumEd25519Provider](https://github.com/danubetech/key-formats-java/blob/main/src/main/java/com/danubetech/keyformats/crypto/provider/impl/NaClSodiumEd25519Provider.java) service.

Default services are configured here:

https://github.com/danubetech/key-formats-java/tree/main/src/main/resources/META-INF/services

You can override this in your own project by copying that file and setting a different service implementation (e.g. TinkEd25519Provider instead of NaClSodiumEd25519Provider).

**Comment by hendersonweb** [comment]
Thanks a lot @peacekeeper . TinkEd25519Provider works fine.

**Comment by peacekeeper** [comment]
Great..! If you don't have any other questions, can we close this issue?

**Comment by hendersonweb** [comment]
Ya definitely. Thanks.

**Comment by Muthurajj** [comment]
> 

How to change in jar file

**Comment by peacekeeper** [comment]
@Muthurajj I'm sorry could you clarify your question? Maybe you could create a new issue in this repository?
